jobs:
  updateBB:
    name: Update Betterbird
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5
      - if: matrix.os == 'ubuntu-latest'
        name: Config git for github-actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Update betterbird
        run: |+
          cd pkgs/betterbird-mac
          sh update.sh
      - name: Commit and push changes.
        run: >
          if [ "$(git status --porcelain)" ]; then
            git add .;
            git commit -m "action: update betterbird-mac";
            git push;
          fi
    strategy:
      matrix:
        os:
          - ubuntu-latest
name: Update Betterbird
"on":
  schedule:
    - cron: 3 2 * * *
  workflow_dispatch: {}
